### ISSUE TITLE
Non-embed mode?

### ISSUE THREAD

**Issue by nopeless** [nebularg/actions-discord-webhook#2]
What should I do if I want to send a message without the embed? (so I can add pings)

@nebularg

**Comment by nebularg** [comment]
If you fork the action, you can add a `"content": "<@&123>",` line before `"embeds": [` to the json and it'll ping that role id in the message before the embed. Although I guess it would be easy to just add an option to set the message from the workflow

**Comment by nopeless** [comment]
@nebularg thanks
